from __future__ import annotations

from app.constants import LANGUAGES, SUBSCRIPTION_PLANS


TEXTS: dict[str, dict[str, str]] = {
    "en": {
        "welcome": "Welcome! Before chatting, please subscribe to all required channels.",
        "check_subscription": "Check subscription",
        "subscription_required": "You need to subscribe to all required channels to continue.",
        "channel_bonus_offer": "You can subscribe to the channel and get 20 more free messages, or choose a paid package.",
        "channel_bonus_granted": "Nice, 20 extra free messages have been added.",
        "choose_language": "Choose your language.",
        "choose_avatar": "Choose an avatar for chatting.",
        "main_menu": "Main menu",
        "language_updated": "Language updated.",
        "avatar_selected": "Avatar selected. You can start chatting.",
        "no_avatar_selected": "Please choose an avatar first.",
        "free_limit_reached": "Your free limit is over. Choose a subscription plan to continue.",
        "subscription_ok": "Subscription check passed.",
        "subscription_missing": "I still can't confirm the required subscriptions.",
        "menu_chat": "Chat",
        "menu_avatar": "Change avatar",
        "menu_language": "Language",
        "menu_subscription": "Messages",
        "menu_gift": "Gifts",
        "menu_premium": "Premium photos",
        "admin_menu": "Admin menu",
        "stats_empty": "No stats yet.",
        "gift_no_photos": "No new photos are available for this avatar right now.",
        "gift_choose": "Choose a gift.",
        "gift_success": "Gift sent successfully.",
        "gift_locked": "This gift does not unlock a premium photo.",
        "gift_empty": "No gifts available yet.",
        "choose_button": "Choose",
        "stars_unit": "Stars",
        "messages_unit_one": "message",
        "messages_unit_many": "messages",
        "plan_not_found": "Plan not found.",
        "gift_not_found": "Gift not found.",
        "choose_avatar_first": "Choose avatar first.",
        "unknown_gift": "Unknown gift.",
        "payment_success": "Payment successful. Balance added: {quota}",
        "unknown_payment_payload": "Unknown payment payload.",
        "avatar_not_found": "Avatar not found.",
        "admin_statistics": "Statistics",
        "admin_avatars": "Avatars",
        "admin_gifts": "Gifts",
        "admin_add_channel": "Add channel",
        "admin_channels": "Channels",
        "admin_broadcast": "Broadcast",
        "admin_send_user": "Send user",
        "admin_grant_balance": "Grant balance",
        "admin_download_db": "Download DB",
        "admin_add_avatar": "Add avatar",
        "admin_edit_avatars": "Edit avatars",
        "admin_edit_channels": "Edit channels",
        "admin_back": "Back to admin",
        "admin_cancel": "Cancel",
        "admin_add_gift": "Add gift",
        "admin_edit_gifts": "Edit gifts",
        "admin_stats_day": "Day",
        "admin_stats_month": "Month",
        "admin_stats_all": "All time",
        "admin_inline_main_photo": "Main photo",
        "admin_inline_name": "Name",
        "admin_inline_description": "Description",
        "admin_inline_link": "Link",
        "admin_inline_system_prompt": "System prompt",
        "admin_inline_upload_lite": "Upload lite photos",
        "admin_inline_upload_premium": "Upload premium photos",
        "admin_inline_toggle_active": "Toggle active",
        "admin_inline_delete": "Delete",
        "admin_inline_skip": "Skip",
        "admin_inline_done": "Done",
        "admin_inline_photo": "Photo",
        "admin_inline_title": "Title",
        "admin_inline_price": "Price",
        "admin_choose_period": "Choose period for statistics:",
        "admin_period": "Period",
        "admin_users": "Users",
        "admin_messages": "Messages",
        "admin_payments": "Payments",
        "admin_stars": "Stars",
        "admin_top_avatar_messages": "Top avatar messages",
        "admin_avatar_management": "Avatar management",
        "admin_channel_management": "Channel management",
        "admin_gift_management": "Gift management",
        "admin_send_avatar_slug": "Send avatar slug.",
        "admin_send_avatar_name": "Send avatar display name.",
        "admin_send_avatar_description": "Send avatar description.",
        "admin_send_avatar_system_prompt": "Send avatar system prompt.",
        "admin_send_avatar_main_photo": "Send main photo for this avatar, or press Skip.",
        "admin_avatar_created": "Avatar created: id={id}",
        "admin_main_photo_saved": "Main photo saved.",
        "admin_send_lite_media": "Now send lite photos or .zip for this avatar, or press Skip / Done.",
        "admin_send_premium_media": "Now send premium photos or .zip for this avatar, or press Skip / Done.",
        "admin_avatar_setup_finished": "Avatar setup finished for avatar {id}. Default upload target switched to lite photos.",
        "admin_choose_avatar_to_edit": "Choose avatar to edit:",
        "admin_choose_channel_to_edit": "Choose channel to edit:",
        "admin_send_gift_slug": "Send gift slug.",
        "admin_send_gift_title": "Send gift title.",
        "admin_send_gift_description": "Send gift description.",
        "admin_send_gift_price": "Send gift price in Stars.",
        "admin_send_numeric_price": "Send numeric price, for example 150.",
        "admin_send_gift_photo": "Send gift photo, or press Skip.",
        "admin_gift_created": "Gift created: id={id}",
        "admin_choose_gift_to_edit": "Choose gift to edit:",
        "admin_gift_not_found": "Gift not found.",
        "admin_gift_title": "Title",
        "admin_price": "Price",
        "admin_description": "Description",
        "admin_active": "Active",
        "admin_gift_summary": "Gift #{id}\nTitle: {title}\nPrice: {price}\nDescription: {description}\nActive: {active}",
        "admin_gift_active_toggled": "Gift active={active}",
        "admin_send_new_gift_photo": "Send new gift photo.",
        "admin_send_new_value_for": "Send new value for {field}.",
        "admin_gift_photo_updated": "Gift photo updated for gift {id}",
        "admin_gift_field_updated": "Gift {field} updated for gift {id}",
        "admin_avatar_summary": "Avatar #{id}\nName: {name}\nDescription: {description}\nActive: {active}",
        "admin_avatar_active_toggled": "Avatar active={active}",
        "admin_upload_target_set": "Upload target set to avatar {id} ({name}), {label} photos. {suffix}",
        "admin_upload_suffix_premium": "Now send photos without caption.",
        "admin_upload_suffix_lite": "Now send photos or .zip without caption.",
        "admin_send_new_main_photo": "Send new main photo for this avatar.",
        "admin_send_new_display_name": "Send new display name.",
        "admin_send_new_description": "Send new description.",
        "admin_send_new_system_prompt": "Send new system prompt.",
        "admin_main_photo_updated": "Main photo updated for avatar {id}",
        "admin_avatar_field_updated": "{field} updated for avatar {id}",
        "admin_use_avatar_format": "Format: /use_avatar 12",
        "admin_current_upload_target": "Current upload target set to avatar {id} ({name}), lite photos",
        "admin_avatar_context_cleared": "Avatar upload context cleared.",
        "admin_broadcast_photo_sent": "Broadcast photo sent to {sent} users.",
        "admin_unlock_photo_price": "Send price in Stars for unlocking this photo.",
        "admin_unlock_video_price": "Send price in Stars for unlocking this video.",
        "admin_premium_photo_uploaded": "Premium photo uploaded. Send price in Stars.",
        "admin_lite_photo_saved": "Lite photo saved to avatar {id}",
        "admin_avatar_not_selected_upload": "Avatar is not selected. Use /use_avatar 12 or create a new avatar first.",
        "admin_premium_upload_one_by_one": "Premium photos need individual price and description, so upload them one by one.",
        "admin_zip_extracted": "Zip extracted to lite photos for avatar {id}",
        "admin_send_numeric_stars_price": "Send numeric price in Stars, for example 250.",
        "admin_premium_photo_saved": "Premium photo saved.",
        "admin_send_channel_chat_id": "Send channel chat id.",
        "admin_send_numeric_chat_id": "Send numeric chat id, for example -1001234567890.",
        "admin_send_channel_title": "Send channel title.",
        "admin_send_channel_link": "Send channel username or invite link, or type skip.",
        "admin_is_channel_private": "Is the channel private? Send 1 or 0.",
        "admin_send_yes_no_10": "Send 1 for yes or 0 for no.",
        "admin_requires_join_request": "Does it require join request approval? Send 1 or 0.",
        "admin_channel_saved": "Channel saved: {title}",
        "admin_channel_not_found": "Channel not found.",
        "admin_channel_summary": "Channel #{id}\nTitle: {title}\nChat ID: {chat_id}\nLink: {link}\nPrivate: {is_private}\nJoin request: {join_request}\nActive: {active}",
        "admin_channel_active_toggled": "Channel active={active}",
        "admin_channel_deleted": "Channel deleted: {title}",
        "admin_avatar_deleted": "Avatar deleted: {name}",
        "admin_send_new_channel_title": "Send new channel title.",
        "admin_send_new_channel_link": "Send new channel link or username, or type skip.",
        "admin_send_new_channel_private": "Send 1 if the channel is private, otherwise 0.",
        "admin_send_new_channel_join_request": "Send 1 if join request approval is required, otherwise 0.",
        "admin_channel_field_updated": "Channel {field} updated for channel {id}",
        "admin_database_not_found": "Database file not found.",
        "admin_database_caption": "SQLite database",
        "admin_send_broadcast_text": "Send broadcast text.",
        "admin_send_button_or_skip": "Send button as label|url or type skip.",
        "admin_send_broadcast_media_or_skip": "Send photo/video for broadcast or type skip.",
        "admin_broadcast_sent": "Broadcast sent to {sent} users.",
        "admin_broadcast_video_sent": "Broadcast video sent to {sent} users.",
        "admin_send_target_user_id": "Send target user telegram id.",
        "admin_send_numeric_user_id": "Send numeric user id.",
        "admin_send_target_username": "Send target username, for example @john.",
        "admin_username_not_found": "User with this username was not found in the database.",
        "admin_send_balance_amount": "Send how many paid messages to add.",
        "admin_send_numeric_amount": "Send a numeric amount, for example 50.",
        "admin_user_not_found": "User not found.",
        "admin_balance_added": "Added {amount} paid messages to @{username}. New balance: {balance}",
        "admin_send_text_or_caption": "Send text or caption.",
        "admin_send_media_or_skip": "Send photo/video or type skip.",
        "admin_message_sent": "Message sent.",
        "admin_send_numeric_stars_amount": "Send numeric Stars amount, for example 2000.",
        "admin_paid_media_sent": "Paid media sent.",
        "admin_target_user_blocked_bot": "This user blocked the bot, so the message cannot be delivered.",
        "admin_avatar_slug_taken": "This slug is already taken. Enter another one.",
    },
    "ru": {
        "welcome": "Привет! Перед началом общения подпишитесь на все обязательные каналы.",
        "check_subscription": "Проверить подписку",
        "subscription_required": "Чтобы продолжить, нужно подписаться на все обязательные каналы.",
        "channel_bonus_offer": "Вы можете подписаться на канал и получить еще 20 бесплатных сообщений или выбрать платный пакет.",
        "channel_bonus_granted": "Готово, вам добавлено еще 20 бесплатных сообщений.",
        "choose_language": "Выберите язык.",
        "choose_avatar": "Выберите аватара для общения.",
        "main_menu": "Главное меню",
        "language_updated": "Язык обновлен.",
        "avatar_selected": "Аватар выбран. Можно начинать общение.",
        "no_avatar_selected": "Сначала выберите аватара.",
        "free_limit_reached": "Бесплатный лимит закончился. Выберите тариф, чтобы продолжить.",
        "subscription_ok": "Проверка подписки пройдена.",
        "subscription_missing": "Пока не удалось подтвердить обязательные подписки.",
        "menu_chat": "Чат",
        "menu_avatar": "Сменить аватара",
        "menu_language": "Язык",
        "menu_subscription": "Сообщения",
        "menu_gift": "Подарки",
        "menu_premium": "Премиум фото",
        "admin_menu": "Админ меню",
        "stats_empty": "Статистики пока нет.",
        "gift_no_photos": "Для этого аватара пока нет новых фото.",
        "gift_choose": "Выберите подарок.",
        "gift_success": "Подарок успешно отправлен.",
        "gift_locked": "Этот подарок не открывает премиум фото.",
        "gift_empty": "Подарков пока нет.",
        "choose_button": "Выбрать",
        "stars_unit": "звёзд",
        "messages_unit_one": "сообщение",
        "messages_unit_many": "сообщений",
        "plan_not_found": "Тариф не найден.",
        "gift_not_found": "Подарок не найден.",
        "choose_avatar_first": "Сначала выберите аватара.",
        "unknown_gift": "Неизвестный подарок.",
        "payment_success": "Оплата прошла успешно. Начислено сообщений: {quota}",
        "unknown_payment_payload": "Неизвестный платёж.",
        "avatar_not_found": "Аватар не найден.",
        "admin_statistics": "Статистика",
        "admin_avatars": "Аватары",
        "admin_gifts": "Подарки",
        "admin_add_channel": "Добавить канал",
        "admin_channels": "Каналы",
        "admin_broadcast": "Рассылка",
        "admin_send_user": "Отправить пользователю",
        "admin_grant_balance": "Выдать баланс",
        "admin_download_db": "Скачать БД",
        "admin_add_avatar": "Добавить аватара",
        "admin_edit_avatars": "Редактировать аватаров",
        "admin_edit_channels": "Редактировать каналы",
        "admin_back": "Назад в админку",
        "admin_cancel": "Отмена",
        "admin_add_gift": "Добавить подарок",
        "admin_edit_gifts": "Редактировать подарки",
        "admin_stats_day": "День",
        "admin_stats_month": "Месяц",
        "admin_stats_all": "Все время",
        "admin_inline_main_photo": "Главное фото",
        "admin_inline_name": "Имя",
        "admin_inline_description": "Описание",
        "admin_inline_link": "Ссылка",
        "admin_inline_system_prompt": "System prompt",
        "admin_inline_upload_lite": "Загрузить lite фото",
        "admin_inline_upload_premium": "Загрузить premium фото",
        "admin_inline_toggle_active": "Переключить активность",
        "admin_inline_delete": "Удалить",
        "admin_inline_skip": "Пропустить",
        "admin_inline_done": "Готово",
        "admin_inline_photo": "Фото",
        "admin_inline_title": "Название",
        "admin_inline_price": "Цена",
        "admin_choose_period": "Выберите период для статистики:",
        "admin_period": "Период",
        "admin_users": "Пользователи",
        "admin_messages": "Сообщения",
        "admin_payments": "Платежи",
        "admin_stars": "Звёзды",
        "admin_top_avatar_messages": "Топ по сообщениям аватаров",
        "admin_avatar_management": "Управление аватарами",
        "admin_channel_management": "Управление каналами",
        "admin_gift_management": "Управление подарками",
        "admin_send_avatar_slug": "Отправьте slug аватара.",
        "admin_send_avatar_name": "Отправьте отображаемое имя аватара.",
        "admin_send_avatar_description": "Отправьте описание аватара.",
        "admin_send_avatar_system_prompt": "Отправьте system prompt аватара.",
        "admin_send_avatar_main_photo": "Отправьте главное фото для этого аватара или нажмите Skip.",
        "admin_avatar_created": "Аватар создан: id={id}",
        "admin_main_photo_saved": "Главное фото сохранено.",
        "admin_send_lite_media": "Теперь отправьте lite фото или .zip для этого аватара, либо нажмите Skip / Done.",
        "admin_send_premium_media": "Теперь отправьте premium фото для этого аватара, либо нажмите Skip / Done.",
        "admin_avatar_setup_finished": "Настройка аватара завершена для avatar {id}. Цель загрузки по умолчанию переключена на lite фото.",
        "admin_choose_avatar_to_edit": "Выберите аватара для редактирования:",
        "admin_choose_channel_to_edit": "Выберите канал для редактирования:",
        "admin_send_gift_slug": "Отправьте slug подарка.",
        "admin_send_gift_title": "Отправьте название подарка.",
        "admin_send_gift_description": "Отправьте описание подарка.",
        "admin_send_gift_price": "Отправьте цену подарка в Stars.",
        "admin_send_numeric_price": "Отправьте числовую цену, например 150.",
        "admin_send_gift_photo": "Отправьте фото подарка или нажмите Skip.",
        "admin_gift_created": "Подарок создан: id={id}",
        "admin_choose_gift_to_edit": "Выберите подарок для редактирования:",
        "admin_gift_not_found": "Подарок не найден.",
        "admin_gift_title": "Название",
        "admin_price": "Цена",
        "admin_description": "Описание",
        "admin_active": "Активен",
        "admin_gift_summary": "Подарок #{id}\nНазвание: {title}\nЦена: {price}\nОписание: {description}\nАктивен: {active}",
        "admin_gift_active_toggled": "Подарок active={active}",
        "admin_send_new_gift_photo": "Отправьте новое фото подарка.",
        "admin_send_new_value_for": "Отправьте новое значение для поля {field}.",
        "admin_gift_photo_updated": "Фото подарка обновлено для gift {id}",
        "admin_gift_field_updated": "Поле {field} обновлено для gift {id}",
        "admin_avatar_summary": "Аватар #{id}\nИмя: {name}\nОписание: {description}\nАктивен: {active}",
        "admin_avatar_active_toggled": "Аватар active={active}",
        "admin_upload_target_set": "Цель загрузки установлена: аватар {id} ({name}), {label} фото. {suffix}",
        "admin_upload_suffix_premium": "Теперь отправляйте фото без подписи.",
        "admin_upload_suffix_lite": "Теперь отправляйте фото или .zip без подписи.",
        "admin_send_new_main_photo": "Отправьте новое главное фото для этого аватара.",
        "admin_send_new_display_name": "Отправьте новое отображаемое имя.",
        "admin_send_new_description": "Отправьте новое описание.",
        "admin_send_new_system_prompt": "Отправьте новый system prompt.",
        "admin_main_photo_updated": "Главное фото обновлено для аватара {id}",
        "admin_avatar_field_updated": "Поле {field} обновлено для аватара {id}",
        "admin_use_avatar_format": "Формат: /use_avatar 12",
        "admin_current_upload_target": "Текущая цель загрузки: аватар {id} ({name}), lite фото",
        "admin_avatar_context_cleared": "Контекст загрузки аватара очищен.",
        "admin_broadcast_photo_sent": "Фото-рассылка отправлена {sent} пользователям.",
        "admin_unlock_photo_price": "Отправьте цену в Stars для открытия этого фото.",
        "admin_unlock_video_price": "Отправьте цену в Stars для открытия этого видео.",
        "admin_premium_photo_uploaded": "Premium фото загружено. Отправьте цену в Stars.",
        "admin_lite_photo_saved": "Lite фото сохранено для аватара {id}",
        "admin_avatar_not_selected_upload": "Аватар не выбран. Используйте /use_avatar 12 или сначала создайте нового аватара.",
        "admin_premium_upload_one_by_one": "Premium фото требуют отдельную цену и описание, поэтому загружайте их по одному.",
        "admin_zip_extracted": "Zip распакован в lite фото для аватара {id}",
        "admin_send_numeric_stars_price": "Отправьте числовую цену в Stars, например 250.",
        "admin_premium_photo_saved": "Premium фото сохранено.",
        "admin_send_channel_chat_id": "Отправьте chat id канала.",
        "admin_send_numeric_chat_id": "Отправьте числовой chat id, например -1001234567890.",
        "admin_send_channel_title": "Отправьте название канала.",
        "admin_send_channel_link": "Отправьте username канала или invite link, либо напишите skip.",
        "admin_is_channel_private": "Канал приватный? Отправьте 1 или 0.",
        "admin_send_yes_no_10": "Отправьте 1 для yes или 0 для no.",
        "admin_requires_join_request": "Нужно подтверждение join request? Отправьте 1 или 0.",
        "admin_channel_saved": "Канал сохранён: {title}",
        "admin_channel_not_found": "Канал не найден.",
        "admin_channel_summary": "Канал #{id}\nНазвание: {title}\nChat ID: {chat_id}\nСсылка: {link}\nПриватный: {is_private}\nJoin request: {join_request}\nАктивен: {active}",
        "admin_channel_active_toggled": "Канал active={active}",
        "admin_channel_deleted": "Канал удалён: {title}",
        "admin_avatar_deleted": "Аватар удалён: {name}",
        "admin_send_new_channel_title": "Отправьте новое название канала.",
        "admin_send_new_channel_link": "Отправьте новую ссылку или username канала, либо напишите skip.",
        "admin_send_new_channel_private": "Отправьте 1, если канал приватный, иначе 0.",
        "admin_send_new_channel_join_request": "Отправьте 1, если требуется подтверждение join request, иначе 0.",
        "admin_channel_field_updated": "Поле {field} обновлено для канала {id}",
        "admin_database_not_found": "Файл базы данных не найден.",
        "admin_database_caption": "База данных SQLite",
        "admin_send_broadcast_text": "Отправьте текст рассылки.",
        "admin_send_button_or_skip": "Отправьте кнопку в формате label|url или напишите skip.",
        "admin_send_broadcast_media_or_skip": "Отправьте фото/видео для рассылки или напишите skip.",
        "admin_broadcast_sent": "Рассылка отправлена {sent} пользователям.",
        "admin_broadcast_video_sent": "Видео-рассылка отправлена {sent} пользователям.",
        "admin_send_target_user_id": "Отправьте telegram id пользователя.",
        "admin_send_numeric_user_id": "Отправьте числовой user id.",
        "admin_send_target_username": "Отправьте username пользователя, например @john.",
        "admin_username_not_found": "Пользователь с таким username не найден в базе данных.",
        "admin_send_balance_amount": "Отправьте, сколько платных сообщений добавить.",
        "admin_send_numeric_amount": "Отправьте числовое значение, например 50.",
        "admin_user_not_found": "Пользователь не найден.",
        "admin_balance_added": "Пользователю @{username} добавлено {amount} платных сообщений. Новый баланс: {balance}",
        "admin_send_text_or_caption": "Отправьте текст или подпись.",
        "admin_send_media_or_skip": "Отправьте фото/видео или напишите skip.",
        "admin_message_sent": "Сообщение отправлено.",
        "admin_send_numeric_stars_amount": "Отправьте числовое количество Stars, например 2000.",
        "admin_paid_media_sent": "Платный медиафайл отправлен.",
        "admin_target_user_blocked_bot": "Этот пользователь заблокировал бота, поэтому отправка сообщения невозможна.",
        "admin_avatar_slug_taken": "Этот slug уже занят. Введите другой.",
    },
    "uk": {
        "welcome": "Привiт! Перед початком спiлкування пiдпишiться на всi обов'язковi канали.",
        "check_subscription": "Перевiрити пiдписку",
        "subscription_required": "Щоб продовжити, потрiбно пiдписатися на всi обов'язковi канали.",
        "channel_bonus_offer": "Ви можете пiдписатися на канал i отримати ще 20 безкоштовних повiдомлень або вибрати платний пакет.",
        "channel_bonus_granted": "Готово, вам додано ще 20 безкоштовних повiдомлень.",
        "choose_language": "Оберiть мову.",
        "choose_avatar": "Оберiть аватара для спiлкування.",
        "main_menu": "Головне меню",
        "language_updated": "Мову оновлено.",
        "avatar_selected": "Аватара обрано. Можна починати спiлкування.",
        "no_avatar_selected": "Спочатку оберiть аватара.",
        "free_limit_reached": "Безкоштовний лiмiт завершився. Оберiть тариф, щоб продовжити.",
        "subscription_ok": "Перевiрку пiдписки пройдено.",
        "subscription_missing": "Поки не вдалося пiдтвердити обов'язковi пiдписки.",
        "menu_chat": "Чат",
        "menu_avatar": "Змiнити аватара",
        "menu_language": "Мова",
        "menu_subscription": "Повiдомлення",
        "menu_gift": "Подiрунки",
        "menu_premium": "Премiум фото",
        "admin_menu": "Адмін меню",
        "stats_empty": "Статистики поки немає.",
        "gift_no_photos": "Для цього аватара поки немає нових фото.",
        "gift_choose": "Оберiть подарунок.",
        "gift_success": "Подарунок успiшно вiдправлено.",
        "gift_locked": "Цей подарунок не вiдкриває премiум фото.",
        "gift_empty": "Подарункiв поки немає.",
        "choose_button": "Обрати",
        "stars_unit": "зiрок",
        "messages_unit_one": "повiдомлення",
        "messages_unit_many": "повiдомлень",
        "plan_not_found": "Тариф не знайдено.",
        "gift_not_found": "Подарунок не знайдено.",
        "choose_avatar_first": "Спочатку оберiть аватара.",
        "unknown_gift": "Невiдомий подарунок.",
        "payment_success": "Оплату успiшно проведено. Додано повiдомлень: {quota}",
        "unknown_payment_payload": "Невiдомий платiж.",
        "avatar_not_found": "Аватара не знайдено.",
        "admin_statistics": "Статистика",
        "admin_avatars": "Аватари",
        "admin_gifts": "Подарунки",
        "admin_add_channel": "Додати канал",
        "admin_channels": "Канали",
        "admin_broadcast": "Розсилка",
        "admin_send_user": "Надiслати користувачу",
        "admin_grant_balance": "Видати баланс",
        "admin_download_db": "Завантажити БД",
        "admin_add_avatar": "Додати аватара",
        "admin_edit_avatars": "Редагувати аватарiв",
        "admin_edit_channels": "Редагувати канали",
        "admin_back": "Назад в адмінку",
        "admin_cancel": "Скасувати",
        "admin_add_gift": "Додати подарунок",
        "admin_edit_gifts": "Редагувати подарунки",
        "admin_stats_day": "День",
        "admin_stats_month": "Мiсяць",
        "admin_stats_all": "За весь час",
        "admin_inline_main_photo": "Головне фото",
        "admin_inline_name": "Iм'я",
        "admin_inline_description": "Опис",
        "admin_inline_link": "Посилання",
        "admin_inline_system_prompt": "System prompt",
        "admin_inline_upload_lite": "Завантажити lite фото",
        "admin_inline_upload_premium": "Завантажити premium фото",
        "admin_inline_toggle_active": "Перемкнути активнiсть",
        "admin_inline_delete": "Видалити",
        "admin_inline_skip": "Пропустити",
        "admin_inline_done": "Готово",
        "admin_inline_photo": "Фото",
        "admin_inline_title": "Назва",
        "admin_inline_price": "Цiна",
        "admin_choose_period": "Оберiть перiод для статистики:",
        "admin_period": "Період",
        "admin_users": "Користувачi",
        "admin_messages": "Повiдомлення",
        "admin_payments": "Платежi",
        "admin_stars": "Зiрки",
        "admin_top_avatar_messages": "Топ за повiдомленнями аватарiв",
        "admin_avatar_management": "Керування аватарами",
        "admin_channel_management": "Керування каналами",
        "admin_gift_management": "Керування подарунками",
        "admin_send_avatar_slug": "Надiшлiть slug аватара.",
        "admin_send_avatar_name": "Надiшлiть вiдображуване iм'я аватара.",
        "admin_send_avatar_description": "Надiшлiть опис аватара.",
        "admin_send_avatar_system_prompt": "Надiшлiть system prompt аватара.",
        "admin_send_avatar_main_photo": "Надiшлiть головне фото для цього аватара або натиснiть Skip.",
        "admin_avatar_created": "Аватара створено: id={id}",
        "admin_main_photo_saved": "Головне фото збережено.",
        "admin_send_lite_media": "Тепер надiшлiть lite фото або .zip для цього аватара, або натиснiть Skip / Done.",
        "admin_send_premium_media": "Тепер надiшлiть premium фото для цього аватара, або натиснiть Skip / Done.",
        "admin_avatar_setup_finished": "Налаштування аватара завершено для avatar {id}. Цiль завантаження за замовчуванням переключено на lite фото.",
        "admin_choose_avatar_to_edit": "Оберiть аватара для редагування:",
        "admin_choose_channel_to_edit": "Оберiть канал для редагування:",
        "admin_send_gift_slug": "Надiшлiть slug подарунка.",
        "admin_send_gift_title": "Надiшлiть назву подарунка.",
        "admin_send_gift_description": "Надiшлiть опис подарунка.",
        "admin_send_gift_price": "Надiшлiть цiну подарунка в Stars.",
        "admin_send_numeric_price": "Надiшлiть числову цiну, наприклад 150.",
        "admin_send_gift_photo": "Надiшлiть фото подарунка або натиснiть Skip.",
        "admin_gift_created": "Подарунок створено: id={id}",
        "admin_choose_gift_to_edit": "Оберiть подарунок для редагування:",
        "admin_gift_not_found": "Подарунок не знайдено.",
        "admin_gift_title": "Назва",
        "admin_price": "Цiна",
        "admin_description": "Опис",
        "admin_active": "Активний",
        "admin_gift_summary": "Подарунок #{id}\nНазва: {title}\nЦiна: {price}\nОпис: {description}\nАктивний: {active}",
        "admin_gift_active_toggled": "Подарунок active={active}",
        "admin_send_new_gift_photo": "Надiшлiть нове фото подарунка.",
        "admin_send_new_value_for": "Надiшлiть нове значення для поля {field}.",
        "admin_gift_photo_updated": "Фото подарунка оновлено для gift {id}",
        "admin_gift_field_updated": "Поле {field} оновлено для gift {id}",
        "admin_avatar_summary": "Аватар #{id}\nIм'я: {name}\nОпис: {description}\nАктивний: {active}",
        "admin_avatar_active_toggled": "Аватар active={active}",
        "admin_upload_target_set": "Цiль завантаження встановлена: аватар {id} ({name}), {label} фото. {suffix}",
        "admin_upload_suffix_premium": "Тепер надсилайте фото без пiдпису.",
        "admin_upload_suffix_lite": "Тепер надсилайте фото або .zip без пiдпису.",
        "admin_send_new_main_photo": "Надiшлiть нове головне фото для цього аватара.",
        "admin_send_new_display_name": "Надiшлiть нове вiдображуване iм'я.",
        "admin_send_new_description": "Надiшлiть новий опис.",
        "admin_send_new_system_prompt": "Надiшлiть новий system prompt.",
        "admin_main_photo_updated": "Головне фото оновлено для аватара {id}",
        "admin_avatar_field_updated": "Поле {field} оновлено для аватара {id}",
        "admin_use_avatar_format": "Формат: /use_avatar 12",
        "admin_current_upload_target": "Поточна цiль завантаження: аватар {id} ({name}), lite фото",
        "admin_avatar_context_cleared": "Контекст завантаження аватара очищено.",
        "admin_broadcast_photo_sent": "Фото-розсилку надiслано {sent} користувачам.",
        "admin_unlock_photo_price": "Надiшлiть цiну в Stars для вiдкриття цього фото.",
        "admin_unlock_video_price": "Надiшлiть цiну в Stars для вiдкриття цього вiдео.",
        "admin_premium_photo_uploaded": "Premium фото завантажено. Надiшлiть цiну в Stars.",
        "admin_lite_photo_saved": "Lite фото збережено для аватара {id}",
        "admin_avatar_not_selected_upload": "Аватара не вибрано. Використайте /use_avatar 12 або спочатку створiть нового аватара.",
        "admin_premium_upload_one_by_one": "Premium фото потребують окрему цiну та опис, тому завантажуйте їх по одному.",
        "admin_zip_extracted": "Zip розпаковано в lite фото для аватара {id}",
        "admin_send_numeric_stars_price": "Надiшлiть числову цiну в Stars, наприклад 250.",
        "admin_premium_photo_saved": "Premium фото збережено.",
        "admin_send_channel_chat_id": "Надiшлiть chat id каналу.",
        "admin_send_numeric_chat_id": "Надiшлiть числовий chat id, наприклад -1001234567890.",
        "admin_send_channel_title": "Надiшлiть назву каналу.",
        "admin_send_channel_link": "Надiшлiть username каналу або invite link, або напишiть skip.",
        "admin_is_channel_private": "Канал приватний? Надiшлiть 1 або 0.",
        "admin_send_yes_no_10": "Надiшлiть 1 для yes або 0 для no.",
        "admin_requires_join_request": "Потрiбне пiдтвердження join request? Надiшлiть 1 або 0.",
        "admin_channel_saved": "Канал збережено: {title}",
        "admin_channel_not_found": "Канал не знайдено.",
        "admin_channel_summary": "Канал #{id}\nНазва: {title}\nChat ID: {chat_id}\nПосилання: {link}\nПриватний: {is_private}\nJoin request: {join_request}\nАктивний: {active}",
        "admin_channel_active_toggled": "Канал active={active}",
        "admin_channel_deleted": "Канал видалено: {title}",
        "admin_avatar_deleted": "Аватара видалено: {name}",
        "admin_send_new_channel_title": "Надiшлiть нову назву каналу.",
        "admin_send_new_channel_link": "Надiшлiть нове посилання або username каналу, або напишiть skip.",
        "admin_send_new_channel_private": "Надiшлiть 1, якщо канал приватний, iнакше 0.",
        "admin_send_new_channel_join_request": "Надiшлiть 1, якщо потрiбне підтвердження join request, iнакше 0.",
        "admin_channel_field_updated": "Поле {field} оновлено для каналу {id}",
        "admin_database_not_found": "Файл бази даних не знайдено.",
        "admin_database_caption": "База даних SQLite",
        "admin_send_broadcast_text": "Надiшлiть текст розсилки.",
        "admin_send_button_or_skip": "Надiшлiть кнопку у форматi label|url або напишiть skip.",
        "admin_send_broadcast_media_or_skip": "Надiшлiть фото/вiдео для розсилки або напишiть skip.",
        "admin_broadcast_sent": "Розсилку надiслано {sent} користувачам.",
        "admin_broadcast_video_sent": "Вiдео-розсилку надiслано {sent} користувачам.",
        "admin_send_target_user_id": "Надiшлiть telegram id користувача.",
        "admin_send_numeric_user_id": "Надiшлiть числовий user id.",
        "admin_send_target_username": "Надiшлiть username користувача, наприклад @john.",
        "admin_username_not_found": "Користувача з таким username не знайдено в базi даних.",
        "admin_send_balance_amount": "Надiшлiть, скiльки платних повiдомлень додати.",
        "admin_send_numeric_amount": "Надiшлiть числове значення, наприклад 50.",
        "admin_user_not_found": "Користувача не знайдено.",
        "admin_balance_added": "Користувачу @{username} додано {amount} платних повiдомлень. Новий баланс: {balance}",
        "admin_send_text_or_caption": "Надiшлiть текст або пiдпис.",
        "admin_send_media_or_skip": "Надiшлiть фото/вiдео або напишiть skip.",
        "admin_message_sent": "Повiдомлення надiслано.",
        "admin_send_numeric_stars_amount": "Надiшлiть числову кiлькiсть Stars, наприклад 2000.",
        "admin_paid_media_sent": "Платний медiафайл надiслано.",
        "admin_target_user_blocked_bot": "Цей користувач заблокував бота, тому надсилання повiдомлення неможливе.",
        "admin_avatar_slug_taken": "Цей slug вже зайнятий. Введiть iнший.",
    },
}


def tr(language: str, key: str) -> str:
    return TEXTS.get(language, TEXTS["en"]).get(key, key)


def format_channels_message(language: str, channel_links: list[str]) -> str:
    intro = tr(language, "welcome")
    if not channel_links:
        return intro
    return "\n".join([intro, "", *channel_links])


def format_plans(language: str, available_messages: int) -> str:
    header = {
        "en": "Choose a plan:",
        "ru": "Выберите тариф:",
        "uk": "Оберiть тариф:",
    }.get(language, "Choose a plan:")
    available_label = {
        "en": f"Available messages: {available_messages}",
        "ru": f"Доступно сообщений: {available_messages}",
        "uk": f"Доступно повiдомлень: {available_messages}",
    }.get(language, f"Available messages: {available_messages}")
    rows = [available_label, "", header]
    return "\n".join(rows)


def available_languages_text() -> str:
    return "\n".join(LANGUAGES.values())


def format_plan_title(language: str, message_quota: int) -> str:
    if language == "ru":
        unit = tr(language, "messages_unit_one") if message_quota % 10 == 1 and message_quota % 100 != 11 else tr(language, "messages_unit_many")
        return f"{message_quota} {unit}"
    if language == "uk":
        return f"{message_quota} {tr(language, 'messages_unit_many')}"
    if message_quota == 1:
        return f"{message_quota} {tr(language, 'messages_unit_one')}"
    return f"{message_quota} {tr(language, 'messages_unit_many')}"


def format_stars(language: str, amount: int) -> str:
    return f"{amount} {tr(language, 'stars_unit')}"
